config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'posts#index'
  # mount ActionCable.server => '/cable'

  get 'dashboard', to: 'dashboard#overview', as: :dashboard

  resources :chatrooms, only: [:create, :show, :update, :index] do
    resources :messages, only: [:create]
  end

  resources :tagged_user, only: [:create]

  resources :posts, only: [:index, :new, :create, :show]

  resources :user_instruments, only: [:new, :create]

  resources :user_genres, only: [:new, :create]

  resources :profiles, only: [:index, :show]

  patch '/profiles/:id/mark', to: 'profiles#available', as: :toggle_availability

  # social gem routes

  post 'profiles/:id/follow', to: 'profiles#follow', as: :follow
  post 'pages/friendlist/:id/follow', to: 'pages#follow_two', as: :follow_two
  # Don't ask questions I'm just lazy
  get 'pages/friendlist', to: 'pages#friendlist', as: :friendlist
  # I said no questions...
  post 'posts/:id/like', to: 'posts#like', as: :like
  post 'profiles/:profile_id/posts/:id/like', to: 'posts#like_two', as: :like_two
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @profile = User.find(params[:id])
    @chatroom = Chatroom.new
  end

  def index
    @user_genres = UserGenre.all
    @user_instruments = UserInstrument.all
    @genres = Genre.all
    @instruments = Instrument.all

    if params[:query].present?
      @profiles = User.global_search(params[:query])
    else
      @profiles = User.all
    end
  end

  def available
    current_user.availability = !current_user.availability
    current_user.save
    redirect_to profile_path(current_user)
  end

  def follow
    @user = User.find(params[:id])
    @current_user = current_user
    if @current_user.toggle_follow!(@user)
      redirect_to profile_path, notice: "You follow #{@user.username} now"
    else
      redirect_to profile_path, notice: "You unfollowed #{@user.username}"
    end
  end
end

app/views/profiles/index.html.erb
<div class="topbar">
  <div class="topbar-content">
    <div> <%= link_to '<', root_path, class: "back-arrow-small" %> </div>
    <div class="searchbar"> <%= render 'shared/search' %> </div>
  </div>
</div>

<div class="search-profiles-wrapper">

  <h2>Found <%= @profiles.count %> profiles</h2>

  <% @profiles.each do |profile| %>
    <div class="profile-card">
      <div class="image">
        <%= cl_image_tag profile.photo.key, height: 120, width: 120, crop: :fill, class: 'avatar-large' %>
      </div>
      <div class="row">
        <div class="profile-details col-12">
          <p><strong><%= profile.username %></strong></p>
            <p class="font-fix"><strong>Plays:</strong> <%= profile.user_instruments[0].instrument.name %> <br> (<%= profile.user_instruments[0].skill_level %>) <br><br><strong>Genre:</strong> <%= profile.user_genres[0].genre.name %> </p>
        </div>
        <%= link_to '>', profile_path(profile), class: "forward-arrow col-3" %>
      </div>
    </div>
 <% end %>

</div>

app/views/profiles/show.html.erb
<div class="image-div">
  <%= cl_image_tag @profile.photo.key, crop: :fill, class: 'profile-photo' %>
  <div>
    <%= link_to '<', profiles_path, class: "back-arrow" %>
  </div>
</div>
  <div class="avail-msg-fol">
    <div class="availability-button">
      <% if @profile == current_user && @profile.availability %>
      <%= link_to "Available", toggle_availability_path, method: :patch, class: "button-available-div" %>
      <% elsif @profile == current_user %>
      <%= link_to "Unavailable", toggle_availability_path, method: :patch, class: "button-unavailable-div" %>
      <% elsif @profile != current_user && @profile.availability %>
      <div class="button-available"> Available</div>
      <% else %>
      <div class="button-unavailable"> Unavailable </div>
      <% end %>
    </div>

    <div class="follow-unfollow">
      <% if @profile != current_user %>
      <!-- FOLLOW BUTTON -->
      <div class="profile-buttons">
        <% if @profile.followed_by?(current_user) %>
        <%= link_to follow_path, method: :post do %>
        <div class="button-follow"> Unfollow </div>
        <!-- <i class="fas fa-user-plus action-buttons"></i> -->
        <% end %>
        <% else %>
        <%= link_to follow_path, method: :post do %>
        <div class="button-unfollow"> Follow </div>
        <!-- <i class="fas fa-user-plus action-buttons follow"></i> -->
        <% end %>
        <% end %>
      </div>
    </div>
    <div class="message-button">
      <!-- CHAT BUTTON -->
      <%= form_for @chatroom do |f| %>
      <%= f.hidden_field :receiver, value: @profile.id %>
      <%= f.hidden_field :sender, value: current_user.id %>
      <%= f.hidden_field :name, value: "#{current_user.username} jams with #{@profile.username}" %>
      <%= button_tag type: 'submit', value: "Message", class: "button-message", id: "register-button" do %>
      <p>Message</p>
      <!-- <i class="" aria-hidden="true"></i> -->
      <% end %>
      <% end %>
    </div>
    <% end %>
  </div>

<div class="info-wrapper">

  <div class="profile-info">
    <div class="name-location">
      <h5> <%= @profile.username %></h5>
      <% address = @profile.address.split(',') %>
      <p class="body-text"> <%= address[-3] %></p>
    </div>
    <div class="fol-fol">
      <div class="followers">
        <%= @profile.followers(User).count %> <p class="body-text">Followers</p>
      </div>
      <div class="following">
        <%= @profile.followees(User).count %> <p class="body-text"> Following </p>
      </div>
    </div>
  </div>

  <!-- INSTRUMENTS AND GENRES -->
  <div class="instrument-genre">
    <div class="instrument-genre-instrument">
      <p> Instruments: </p>
      <% @profile.user_instruments.each do |instrument| %>
      <p class="body-text"> <%= instrument.instrument.name %> (<%= instrument.skill_level %>) </p>
      <% end %>
    </div>
    <div class="instrument-genre-genre">
      <p> Genres: </p>
      <% @profile.user_genres.each do |genre| %>
      <p class="body-text genre-tag"> <%= genre.genre.name %> </p>
      <% end %>
    </div>
  </div>
  <!-- --------------------- -->
</div>


<!-- USER POSTS------ -->

<div class="user-posts">
  <% if @profile == current_user %>
  <div class="post-button-profile">

    <%= link_to '', new_post_path, class: "fas fa-plus-circle" %>
  </div>
  <% end %>
  <% @profile.posts.sort {|a, b| b <=> a}.each do |post| %>
  <div class="post-content">
    <div class="post-header">
      <%= cl_image_tag post.user.photo.key, height: 100, width: 100, crop: :fill, class: 'avatar-small user-image' %>
      <div class="post-username">
        <%= post.user.username.capitalize %> <p> shared a new post</p>
      </div>
    </div>
    <div class="post-media">
      <% if post.mediafiles != nil && post.mediafiles != "" %>
      <% youtube_id = YouTubeAddy.extract_video_id(post.mediafiles) %>
      <% url = "https://www.youtube.com/embed/#{youtube_id}" %>
      <iframe class="post-image lozad" width="100%" data-src="<%= url %>?rel=0&modestbranding=0&autohide=1&showinfo=0&controls=1" frameborder ="0" allowfullscreen></iframe>
      <%end %>
      <% post.pictures.each do |p| %>
      <%= cl_image_tag p.key, width: 372, class: 'post-image'  %>
      <% end %>
      <div class="caption">
        <p><%= post.caption %></p>
      </div>
    </div>
    <div class="post-footer">
      <div class="like-buttons">
        <% if post.liked_by?(current_user) %>

          <%= link_to "/profiles/#{post.user.id}/posts/#{post.id}/like", method: :post, remote: true do %>
            <i class="fas fa-heart buttons"></i>
          <% end %>
        <% else %>
          <%= link_to "/profiles/#{post.user.id}/posts/#{post.id}/like", method: :post, remote: true do %>
            <i class="far fa-heart buttons"></i>
          <% end %>
        <% end %>
        <p class="like-count"><%= post.likers_count %></p>
      </div>
    </div>

  </div>
  <% end %>
</div>
</div>