config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'posts#index'
  # mount ActionCable.server => '/cable'

  get 'dashboard', to: 'dashboard#overview', as: :dashboard

  resources :chatrooms, only: [:create, :show, :update, :index] do
    resources :messages, only: [:create]
  end

  resources :tagged_user, only: [:create]

  resources :posts, only: [:index, :new, :create, :show]

  resources :user_instruments, only: [:new, :create]

  resources :user_genres, only: [:new, :create]

  resources :profiles, only: [:index, :show]

  patch '/profiles/:id/mark', to: 'profiles#available', as: :toggle_availability

  # social gem routes

  post 'profiles/:id/follow', to: 'profiles#follow', as: :follow
  post 'pages/friendlist/:id/follow', to: 'pages#follow_two', as: :follow_two
  # Don't ask questions I'm just lazy
  get 'pages/friendlist', to: 'pages#friendlist', as: :friendlist
  # I said no questions...
  post 'posts/:id/like', to: 'posts#like', as: :like
  post 'profiles/:profile_id/posts/:id/like', to: 'posts#like_two', as: :like_two
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :asker, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/genre.rb
class Genre < ApplicationRecord


  has_many :user_genres
  has_many :users, through: :user_genres
  validates :name, presence: true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :user_instruments
  has_many :users, through: :user_instruments
  validates :name, presence: true
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  validates :content, presence: true

  after_create :broadcast_message

  def broadcast_message
    ActionCable.server.broadcast("chatroom_#{chatroom.id}", {
      message_partial: ApplicationController.renderer.render(
        partial: "messages/message",
        locals: { message: self, user_is_messages_author: false }
        ),
      current_user_id: user.id
    })
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :tagged_users
  has_many_attached :pictures
  has_one_attached :video
  has_one_attached :audio

  validates :caption, presence: true

  # social gem
  acts_as_likeable
end

app/models/tagged_user.rb
class TaggedUser < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch::Model

  # for geocoder
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  pg_search_scope :global_search, against: [:username],
  associated_against: {
    instruments: [:name],
    # user_instruments: [:skill_level],
    genres: [:name]
    # posts: [:caption]
  },
  using: {
    tsearch: {
      prefix: true,
      dictionary: "english"
    },
    trigram: {
    }
  }

  has_many :user_instruments, dependent: :destroy
  has_many :instruments, through: :user_instruments
  has_many :user_genres, dependent: :destroy
  has_many :genres, through: :user_genres
  has_many :messages
  has_many :conversations
  has_many :chatrooms, through: :messages
  has_many :posts, dependent: :destroy
  has_one_attached :photo
  has_many :friendships_as_asker, source: :friendships, foreign_key: :asker_id
  has_many :friendships_as_receiver, source: :friendships, foreign_key: :receiver_id

  validates :username, presence: true, uniqueness: true
  validates :address, presence: true
  # Check devise validations
  validates :photo, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  # social gem
  acts_as_follower
  acts_as_followable
  acts_as_liker
  acts_as_likeable
  acts_as_mentionable
end

app/models/user_genre.rb
class UserGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  accepts_nested_attributes_for :genre
end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord
  SKILL_LEVELS = ['Beginner', 'Intermediate', 'Expert']
  belongs_to :instrument
  belongs_to :user

  validates :skill_level, inclusion: { in: SKILL_LEVELS }
  accepts_nested_attributes_for :instrument
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
      @chatroom,
      render_to_string(partial: "message", locals: { message: @message })
      )
      redirect_to chatroom_path(@chatroom, anchor: "message-#{@message.id}")
    else
      render "chatrooms/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def friendlist
    @users = User.all
    @following = current_user.followees(User)
    @followers = current_user.followers(User)
  end

  def follow_two
    @user = User.find(params[:id])
    @current_user = current_user
    if @current_user.toggle_follow!(@user)
      redirect_to friendlist_path, notice: "You follow #{@user.username} now"
    else
      redirect_to friendlist_path, notice: "You unfollowed #{@user.username}"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    # @user = User.find(params[:user_id])
    @post = Post.new(post_params)
    youtube_error = true
    @post.user = current_user

    if @post.mediafiles == ""
      youtube_error = false
     elsif YouTubeAddy.extract_video_id(@post.mediafiles) != nil  && YouTubeAddy.extract_video_id(@post.mediafiles).length == 11
       youtube_error = false
    else
      youtube_error = true
    end
     if @post.valid? && youtube_error == false
      @post.save
      redirect_to posts_path
    else
        render :new
    end

  end

    def show
      @posts = Posts.find(params[:id])
    end

    def index
      @posts = Post.all
    end

    def like
      @post = Post.find(params[:id])
      @current_user = current_user
      if @current_user.toggle_like!(@post)
      end
    end

  # No questions! I'm lazy...

  def like_two
    @post = Post.find(params[:id])
    @current_user = current_user
    if @current_user.toggle_like!(@post)
    end
  end

private

  def post_params
    params.require(:post).permit(:mediafiles, :caption, pictures: [])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @profile = User.find(params[:id])
    @chatroom = Chatroom.new
  end

  def index
    @user_genres = UserGenre.all
    @user_instruments = UserInstrument.all
    @genres = Genre.all
    @instruments = Instrument.all

    if params[:query].present?
      @profiles = User.global_search(params[:query])
    else
      @profiles = User.all
    end
  end

  def available
    current_user.availability = !current_user.availability
    current_user.save
    redirect_to profile_path(current_user)
  end

  def follow
    @user = User.find(params[:id])
    @current_user = current_user
    if @current_user.toggle_follow!(@user)
      redirect_to profile_path, notice: "You follow #{@user.username} now"
    else
      redirect_to profile_path, notice: "You unfollowed #{@user.username}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= meta_title %></title>
  <meta name="description" content="<%= meta_description %>">

  <!-- Facebook Open Graph data -->
  <meta property="og:title" content="<%= meta_title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= meta_image %>" />
  <meta property="og:description" content="<%= meta_description %>" />
  <meta property="og:site_name" content="<%= meta_title %>" />

  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable"  content="yes">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
  <%= render 'shared/ios_pwa_links' %>
</head>

<body>

  <div class="wrapper">
    <%= yield %>
    <div class="footer-blocker"></div>
  </div>

  <%= render 'shared/flashes' %>
  <%= render 'components/footer' %>

</body>
</html>

app/views/pages/friendlist.html.erb
<div class="topbar">
  <div class="topbar-content-messages">
  <h3>Followers</h3>
  </div>
</div>

<div class="search-profiles-wrapper">

    <h4>Following <%= @following.count %> profiles</h4>

    <% @following.each do |follow| %>

      <div class="card-friendlist">
        <%= cl_image_tag @users.find(follow.id).photo.key %>
        <div class="card-friendlist-infos">
          <h2><%= @users.find(follow.id).username %></h2>
          <div class="friendlist-buttons">
            <% if follow.followed_by?(current_user) %>
              <%= link_to follow_two_path(follow.id), method: :post do %>
                <i class="fas fa-heart-broken buttons"></i>
              <% end %>
            <% end %>
            <i class="fas fa-comments buttons"></i>
          </div>
        </div>
      </div>

    <% end %>

    <hr>

    <h4>You have <%= @followers.count %> followers</h4>

    <% @followers.each do |follower| %>

      <div class="card-friendlist">
        <%= cl_image_tag @users.find(follower.id).photo.key %>
        <div class="card-friendlist-infos">
          <h2><%= @users.find(follower.id).username %></h2>
          <div class="friendlist-buttons">
            <i class="fas fa-comments buttons"></i>
          </div>
        </div>
      </div>

    <% end %>
  </div>

app/views/pages/home.html.erb
<h1>Site under construction 🚧</h1>
<p>comming soon™</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_search.html.erb
<%= form_tag profiles_path, method: :get do %>
<div class="search-form-control form-inline">
  <%= text_field_tag :query,
  params[:query],
  class: "form-control input-field apple",
    placeholder: "Instrument, genre or user"
    %>
    <%= submit_tag "Search", class: "btn-search" %>
  </div>
  <% end %>