config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'posts#index'
  # mount ActionCable.server => '/cable'

  get 'dashboard', to: 'dashboard#overview', as: :dashboard

  resources :chatrooms, only: [:create, :show, :update, :index] do
    resources :messages, only: [:create]
  end

  resources :tagged_user, only: [:create]

  resources :posts, only: [:index, :new, :create, :show]

  resources :user_instruments, only: [:new, :create]

  resources :user_genres, only: [:new, :create]

  resources :profiles, only: [:index, :show]

  patch '/profiles/:id/mark', to: 'profiles#available', as: :toggle_availability

  # social gem routes

  post 'profiles/:id/follow', to: 'profiles#follow', as: :follow
  post 'pages/friendlist/:id/follow', to: 'pages#follow_two', as: :follow_two
  # Don't ask questions I'm just lazy
  get 'pages/friendlist', to: 'pages#friendlist', as: :friendlist
  # I said no questions...
  post 'posts/:id/like', to: 'posts#like', as: :like
  post 'profiles/:profile_id/posts/:id/like', to: 'posts#like_two', as: :like_two
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :tagged_users
  has_many_attached :pictures
  has_one_attached :video
  has_one_attached :audio

  validates :caption, presence: true

  # social gem
  acts_as_likeable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    # @user = User.find(params[:user_id])
    @post = Post.new(post_params)
    youtube_error = true
    @post.user = current_user

    if @post.mediafiles == ""
      youtube_error = false
     elsif YouTubeAddy.extract_video_id(@post.mediafiles) != nil  && YouTubeAddy.extract_video_id(@post.mediafiles).length == 11
       youtube_error = false
    else
      youtube_error = true
    end
     if @post.valid? && youtube_error == false
      @post.save
      redirect_to posts_path
    else
        render :new
    end

  end

    def show
      @posts = Posts.find(params[:id])
    end

    def index
      @posts = Post.all
    end

    def like
      @post = Post.find(params[:id])
      @current_user = current_user
      if @current_user.toggle_like!(@post)
      end
    end

  # No questions! I'm lazy...

  def like_two
    @post = Post.find(params[:id])
    @current_user = current_user
    if @current_user.toggle_like!(@post)
    end
  end

private

  def post_params
    params.require(:post).permit(:mediafiles, :caption, pictures: [])
  end
end

app/views/posts/index.html.erb
<div class="topbar">
  <div class="topbar-content">
    <%= cl_image_tag ('https://res.cloudinary.com/benjriethmuller/image/upload/v1591781535/Jamable_Logo_Wordmark_White_izwqep.png'), width: 100 %>
    <div class="post-button">
      <%= link_to '', new_post_path, class: "fas fa-plus-circle" %>
    </div>
  </div>
</div>

<div class="feed-wrapper">
  <% @posts.sort {|a, b| b <=> a}.each do |post| %>
  <div class="post-content">
    <div class="post-header">
      <%= link_to (cl_image_tag post.user.photo.key, height: 100, width: 100, crop: :fill, class: 'avatar-small user-image'), profile_path(post.user) %>
      <div class="post-username">
        <%= link_to "#{post.user.username.capitalize}", profile_path(post.user), class: 'no-link-deko' %> <p> shared a new post</p>
      </div>
    </div>
    <div class="post-media">
      <% if post.mediafiles != nil && post.mediafiles != "" %>
      <% youtube_id = YouTubeAddy.extract_video_id(post.mediafiles) %>
      <% url = "https://www.youtube.com/embed/#{youtube_id}" %>
      <iframe class="post-image lozad" width="100%" data-src="<%= url %>?rel=0&modestbranding=0&autohide=1&showinfo=0&controls=1" frameborder ="0" allowfullscreen></iframe>
      <%end %>
      <% post.pictures.each do |p| %>
      <%= cl_image_tag p.key, width: 372, class: 'post-image'  %>
      <% end %>
      <div class="caption">
        <%= simple_format(post.caption) %>

      </div>
    </div>
    <div class="post-footer">
      <div class="like-buttons">
        <% if post.liked_by?(current_user) %>
        <%= link_to like_path(post), method: :post, remote: true do %>
        <i class="fas fa-heart buttons"></i>
        <% end %>
        <% else %>
        <%= link_to like_path(post), method: :post, remote: true do %>
        <i class="far fa-heart buttons"></i>
        <% end %>
        <% end %>
        <p class="like-count"><%= post.likers_count %></p>
      </div>
    </div>

  </div>

  <% end%>

</div>

app/views/posts/new.html.erb
  <div class="topbar">
    <div class="topbar-content-messages">
    <h3>New post</h3>
    </div>
  </div>

  <div class="container-signup">

    <%= simple_form_for @post do |f| %>
      <div class="signup-wrapper">
<!--         <h2>New post</h2> -->
        <%= f.input :pictures, as: :file, input_html: {multiple: true} %>
        <%= f.input :mediafiles, as: :text, input_html: {rows: 1}, placeholder: "optional YouTube link" %>
        <%= f.input :caption, as: :text, input_html: {rows: 10}, placeholder: "Add a caption" %>
        <%= f.button :submit, "Create post", class: "login-button w-100" %>
      </div>
    <% end %>

  </div>